### ISSUE TITLE
2FA not working

### ISSUE THREAD

**Issue by thieren** [thieren/eufy-test-client#1]
As pointed out here https://github.com/homebridge-eufy-security/plugin/issues/38#issuecomment-1143900682 2fa is not working

**Comment by thieren** [comment]
Hey @njuart

I'll have to test myself. In theory there should have been a command line prompt to ask for the code. Have to setup an account to test this myself...

**Comment by njuart** [comment]
Sure, tried a couple of times but there was no request to enter code

**Comment by thieren** [comment]
fixed
